{
 "title": "NetApp HCI - H400 Series Chasis and Server Systems",
 "description": "Hardware Metrics for NetApp H-Series 410C, 300E, 500E, 700E (IPMI)",
 "tags": [
  "netapp hci",
  "ipmi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "platform", "label": "NetApp HCI Compute Platform", "query": "netapp.hci.compute.*" },
   { "name": "hostname", "label": "NetApp HCI Compute Host", "query": "netapp.hci.compute.$platform.*" }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Temperature - $hostname",
   "type": "gauge",
   "description": "Different CPUs have different operating temperatures, so gauge thresholds should probably be customized for the CPU with lowest operating temperatures in your environment.\n\nExample: Intel Xeon Gold 6240Y - Max 74C, so we may want to set orange (warning) at 55C and red (critical) at 65C\n\nNote that Grafana alerts need to be separately configured.",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-CPU1_Temp_processor__3_1_, 'CPU0 Temperature')"
    },
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-CPU2_Temp_processor__3_2_, 'CPU1 Temperature')"
    }
   ]
  },
  {
   "title": "System Board Temperature - $hostname",
   "type": "gauge",
   "description": "Different systems have different operating ranges and different data centers run at different temperatures. Feel free to examine the details of sensor that's measured and adjust Warning and Critical level for your environment. \n\nNote that Grafana alerts need to be separately configured.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-System_Temp_system_board__7_2_, 'Mainboard Temperature')"
    }
   ]
  },
  {
   "title": "BMC Power Consumption - $hostname",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.power-PW_Consumption_power_management_board__21_0_, 'BMC Power Consumption')"
    }
   ]
  },
  {
   "title": "Chassis Fan Speed",
   "type": "bargauge",
   "description": "Several H400 Systems (up to 4) may share the same H400 chassis, so chassis fan metrics aren't host-specific\n\nThis also applies to chassis hosting H-Series 300E, 500E, 700E compute nodes (which may be intermixed between them and also with H410C and even H401S nodes)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.fanspeed-FAN1_fan_cooling__29_1_, 'FAN1')"
    },
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.fanspeed-FAN2_fan_cooling__29_2_, 'FAN2')"
    }
   ]
  },
  {
   "title": "Temperature Indicators - $hostname",
   "type": "graph",
   "description": "This panel serves to help you spot temperature trends in over days or weeks.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-CPU1_Temp_processor__3_1_, 'CPU0 Temp')"
    },
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-CPU2_Temp_processor__3_2_, 'CPU1 Temp')"
    },
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-AOC_NIC_Temp____system_board__7_1_, 'NIC Temp')"
    },
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.temperature-Inlet_Temp_system_board__7_3_, 'Inlet Temp')"
    }
   ]
  },
  {
   "title": "Chassis Fan Speed",
   "type": "graph",
   "description": "Single chassis may be shared among up to 4 compute and/or storage nodes from Gen 1 (H300/H500/H700) and Gen 2 (H410) H-Series systems",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.fanspeed-FAN1_fan_cooling__29_1_, 'Fan1 Speed')"
    },
    {
     "target": "alias(netapp.hci.compute.$platform.$hostname.ipmi.fanspeed-FAN2_fan_cooling__29_2_, 'Fan2 Speed')"
    }
   ]
  }
 ]
}