{
 "title": "NetApp HCI - SolidFire Node",
 "description": "Per node statistics for a SolidFire cluster",
 "tags": [
  "SolidFire",
  "HCI"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "SolidFire Cluster Name", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "Node",
    "label": "SolidFire Node",
    "query": "netapp.solidfire.cluster.$Cluster.node.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Processor, Memory and Network Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$Node CPU Utilization",
   "type": "stat",
   "description": "This value is generally not important as storage node performance is determined by QoS settings and activity of the volumes active on the node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "repeat": "Cluster",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.node.$Node.cpu"
    }
   ]
  },
  {
   "title": "$Node Node Network Utilization",
   "type": "stat",
   "description": "This value is generally not important as storage node performance is much smaller than network bandwidth available on SolidFire nodes.\n\nIt can be of interest in parallel backup or during distributed recovery from failed nodes or disk drives.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "Node",
   "targets": [
    {
     "target": "aliasByNode(netapp.solidfire.cluster.$Cluster.node.$Node.networkUtilizationCluster, 5)"
    }
   ]
  },
  {
   "title": "$Node RAM Utilization",
   "type": "stat",
   "description": "Generally not important, as RAM is appropriately sized for the node to deliver rated IOPS with compression and deduplication enabled",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "Node",
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$Cluster.node.$Node.usedMemory)"
    }
   ]
  },
  { "title": "Node Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$Node Node IOPS",
   "type": "graph",
   "description": "Nodes are not expected to be equally busy, but with many more active volumes than storage nodes, eventually they tend to be similarly busy.\n\nOutliers may appear during storage-offloaded operations (Storage vMotion, for example).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "repeat": "Node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.readOps), 5), 'Read IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.writeOps), 5), 'Write IOPS')"
    },
    {
     "target": "alias(sumSeries(#A,#B),'Total IOPS')",
     "targetFull": "alias(sumSeries(alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.readOps), 5), 'Read IOPS'),alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.writeOps), 5), 'Write IOPS')),'Total IOPS')"
    }
   ]
  },
  { "title": "Storage Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$Node Node iSCSI Network Traffic",
   "type": "graph",
   "description": "iSCSI Network Traffic in bytes per second. \n\nWe can use this chart to check if parallel backup is keeping all storage nodes equally busy, or how much additional bandwidth is used after volume replication traffic is enabled ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "repeat": "Node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.sBytesOut), 'Out')"
    }
   ]
  },
  { "title": "Management Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$Node Node Management Network Traffic",
   "type": "graph",
   "description": "Network traffic on management interface",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "repeat": "Node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesIn), 'In')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.node.$Node.mBytesOut), 'Out')"
    }
   ]
  }
 ]
}