{
 "title": "NetApp HCI - SolidFire Experimental Panels",
 "description": "Experimental SolidFire Panels",
 "tags": [
  "SolidFire",
  "NetApp HCI"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "clusterID", "label": "Cluster Name", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "volumeID",
    "label": "Volume ID",
    "query": "netapp.solidfire.cluster.*.volumeID.*"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "clusterID" },
  {
   "title": "$clusterID - Data Space Utilization and Total Capacity",
   "type": "graph",
   "description": "When Max UsedSpace is hit, cluster has no space to write new data.\n\nMost admins shouldn't wait until the value nonZeroBlocks gets very close to maxUsedSpace (especially if they desire to tolerate the loss of one node) - it is suggested to consider Warning Level which is Max Used Capacity of (N-1) nodes minus  (this value can be set in Cluster settings) 3%)\n\nNote that capacity utilization is updated once per hour (after each Garbage Collection run)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.maxUsedSpace, 'Maximum Block Storage Capacity')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.uniqueBlocksUsedSpace, 'Data Capacity Used by Unique Blocks')"
    }
   ]
  },
  {
   "title": "$clusterID - Metadata Space Utilization and Total Capacity",
   "type": "graph",
   "description": "maxUsedMetadata space is the maximum amount of space available for volume metadata. It does not account for N-1 (node or metadata disk drive loss) so it is recommended to have spare metadata capacity to be able to tolerate the loss of at least one node or metadata disk drive.\n\nIf usedMetadata space is growing quickly, make sure users or automation tools aren't leaving behind unnecessary clones or snapshots.\n\nNote that metadata capacity utilization is updated once per hour (after each Garbage Collection run).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.maxUsedMetadataSpace, 'Maximum Metadata Capacity')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.usedMetadataSpace, 'Used Metadata Capacity')"
    }
   ]
  },
  {
   "title": "$clusterID - Trend in Unique Block Space Use",
   "type": "btplc-trend-box-panel",
   "description": "Trend of change in Unique Block Space Used over observed period of time. \n\nNote that iSCSI clients need to unmap/trim FS in order to release space.\n\nMinimum recommended interval for trend observation is 1 day.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "format": "bytes",
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.uniqueBlocksUsedSpace, 'Active Block Space')"
    }
   ]
  },
  {
   "title": "$clusterID - Trend in Non-Zero Snapshot Use (4kB Blocks)",
   "type": "btplc-trend-box-panel",
   "description": "Trend of change in Non-Zero Snapshot Blocks (1 block = 4kB) over observed period of time \n\nThis figure can grow quickly when first snapshots are created in the cluster,  in which case we should watch its value to see if the growth in snapshot space utilization is concerning. \n\nNote that iSCSI clients need to unmap/trim FS in order to release space.\n\nMinimum recommended interval for trend observation is 1 day.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "targets": [
    {
     "refCount": 1,
     "target": "alias(netapp.solidfire.cluster.$clusterID.snapshotNonZeroBlocks, 'Non-zero Snapshot Blocks')"
    }
   ]
  },
  {
   "title": "$clusterID - Trend in Metadata Space Use",
   "type": "btplc-trend-box-panel",
   "description": "Trend of change in Used Metadata Space over observed period of time.\n\nNote that iSCSI clients need to unmap/trim FS in order to release space.\n\nMinimum recommended interval for trend observation is 1 day.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "format": "bytes",
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.usedMetadataSpace, 'Used Metadata Space')"
    }
   ]
  },
  {
   "title": "$clusterID - Metadata Space used by Snapshots ",
   "type": "graph",
   "description": "Metadata capacity (in bytes) used to preserve snapshots. \n\nChanges in this value may sometime seem odd because the size of Metadata Space used by Snapshots includes Metadata Space used by the original volume (technically that space is used for Snapshot Capacity because is cannot be released as long as there is has at least one snapshot).\n\nNote that iSCSI clients need to unmap/trim FS in order to release block space which lowers the use of metadata.\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(#B, #A), 'Metadata Space Used by Snapshots')",
     "targetFull": "alias(diffSeries(netapp.solidfire.cluster.$clusterID.usedMetadataSpace, netapp.solidfire.cluster.$clusterID.usedMetadataSpaceInSnapshots), 'Metadata Space Used by Snapshots')"
    }
   ]
  },
  { "title": "Volume Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "clusterID" },
  {
   "title": "$clusterID - Volumes with 2X or lower Efficiency",
   "type": "graph",
   "description": "These volumes may be candidates for efficiency improvements. Volumes with efficiency above 2X are not displayed.\n\nThis panel uses new metric paths (HCICollector v0.7) based on Volume IDs and in order to map IDs to Names click on the SolidFire UI link in top right corner of this dashboard and look it up in the SolidFire Web UI.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Compr x Dedupe" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "substr(removeAboveValue(netapp.solidfire.cluster.$clusterID.volumeID.$volumeID.volumeEfficiency, 2), 5, 6)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "$clusterID - Volumes with Burst IOPS Credit > 600K",
   "type": "graph",
   "description": "Potential candidates for lower Burst IO Setting.\n\nYou may want to adjust panel settings or create several similar indicators.\n\nThis panel uses new metric paths (HCICollector v0.7) based on Volume IDs and in order to map IDs to Names click on the SolidFire UI link in top right corner of this dashboard and look it up in the SolidFire Web UI.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "substr(removeBelowValue(netapp.solidfire.cluster.$clusterID.volumeID.$volumeID.burstIOPSCredit, 600000), 5, 6)"
    }
   ]
  }
 ]
}