{
 "title": "NetApp HCI - SolidFire Storage Optimization",
 "description": "Dashboard with storage optimization-focused panels",
 "tags": [
  "SolidFire",
  "HCI"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "clusterID", "label": "Cluster Name", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "volumeID",
    "label": "Volume ID",
    "query": "netapp.solidfire.cluster.*.volumeID.*"
   },
   {
    "name": "accountID",
    "label": "Account ID (Name)",
    "query": "netapp.solidfire.cluster.*.accountID.*"
   },
   {
    "name": "accountIdNum",
    "label": "Account ID (Numeric)",
    "query": "netapp.solidfire.cluster.*.accountID.*"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Space Used & Maximum",
   "type": "graph",
   "description": "When maxUsedSpace is hit, cluster has no space to write new data.\n\nMost users don't wait until nonZeroBlocks get close to maxUsedSpace (especially if they desire to tolerate the loss of one node)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.*.maxUsedSpace)"
    },
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.*.usedSpace)"
    }
   ]
  },
  {
   "title": "Metadata Space Used & Maximum",
   "type": "graph",
   "description": "maxUsedMetadata space is the maximum amount of space available for volume metadata. \n\nIf usedMetadata space is growing quickly, make sure users or automation aren't leaving behind unnecessary clones or snapshots",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.*.maxUsedMetadataSpace)"
    },
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.*.usedMetadataSpace)"
    }
   ]
  },
  {
   "title": "Data Space Utilization Trend",
   "type": "btplc-trend-box-panel",
   "description": "Data capacity utilization trend shows change (% delta) over selected time period and (below) the current utiilzation (% full)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "targets": [
    {
     "target": "asPercent(#C, #A)",
     "targetFull": "asPercent(aliasByMetric(netapp.solidfire.cluster.*.usedSpace), aliasByMetric(netapp.solidfire.cluster.*.maxUsedSpace))"
    }
   ]
  },
  {
   "title": "Metadata Space Utilization Trend",
   "type": "btplc-trend-box-panel",
   "description": "Metadata capacity utilization trend shows change (% delta)  over selected time period and (below) the current utiilzation (% full)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "target": "asPercent(#C, #A)",
     "targetFull": "asPercent(aliasByMetric(netapp.solidfire.cluster.*.usedMetadataSpace), aliasByMetric(netapp.solidfire.cluster.*.maxUsedMetadataSpace))"
    }
   ]
  },
  { "title": "Volume Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Volumes with Compr & Dedupe below 2X",
   "type": "graph",
   "description": "These volumes may be candidates for efficiency improvements\n\nThis panel uses new metric paths (HCICollector v0.7) based on Volume IDs and in order to map IDs to Names click on the SolidFire UI link in top right corner of this dashboard and look it up in the SolidFire Web UI",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Compr x Dedupe" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "substr(removeAboveValue(netapp.solidfire.cluster.*.volumeID.$volumeID.volumeEfficiency, 2), 5, 6)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Volumes with Burst IOPS Credit > 600K",
   "type": "graph",
   "description": "Candidates for lower Burst IO Setting.\n\nYou may want to adjust values and create several similar indicators.\n\nThis panel uses new metric paths (HCICollector v0.7) based on Volume IDs and in order to map IDs to Names click on the SolidFire UI link in top right corner of this dashboard and look it up in the SolidFire Web UI",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "substr(removeBelowValue(netapp.solidfire.cluster.*.volumeID.$volumeID.burstIOPSCredit, 600000), 5, 6)"
    }
   ]
  },
  { "title": "Account Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Account Data Efficiency for all Accounts",
   "type": "graph",
   "description": "Data effficiency (Deduplication x Compression) over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "substr(netapp.solidfire.cluster.$clusterID.accountID.*.accountEfficiency, 4, 6)"
    }
   ]
  },
  {
   "title": "Volume Sizes by Account ID (Name): $accountID",
   "type": "grafana-piechart-panel",
   "description": "Size of all volumes belonging to an account (selected in Name drop-down list at the top)\n\nThis includes thin-provisioned capacity (which is unused capacity) and does not consider data efficiencies",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(netapp.solidfire.cluster.$clusterID.accountID.$accountID.volume.*.volumeSize, 7, 8, 11)"
    }
   ]
  },
  {
   "title": "Volume Efficiency by Numeric Account ID: $accountIdNum",
   "type": "singlestat",
   "description": "Efficiency of data stored on volumes owned by an account (selected from numeric ID drop-down list at the top; this is an inconvenience of storing this data in a location different - see Release Notes for v0.7)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.accountID.$accountIdNum.accountEfficiency, '$accountIdNum')"
    }
   ]
  }
 ]
}