{
 "title": "NetApp HCI - SolidFire Multi-Cluster NOC View",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "netapp.solidfire.cluster.*" }
  ]
 },
 "panels": [
  {
   "title": "$Cluster cluster Utilization %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "repeat": "Cluster",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.clusterUtilization"
    }
   ]
  },
  {
   "title": "$Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "repeat": "Cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readOps), 5), 'Read IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeOps), 5), 'Write IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(sumSeries(netapp.solidfire.cluster.$Cluster.{readOps,writeOps})), 5), 'Total IOPS')"
    }
   ]
  },
  {
   "title": "$Cluster Read/Write Bytes / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "repeat": "Cluster",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readBytes), 5), 'Read Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeBytes), 5), 'Write Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(perSecond(netapp.solidfire.cluster.$Cluster.{readBytes,writeBytes})), 5), 'Total Bytes/s')"
    }
   ]
  },
  {
   "title": "$Cluster Drive Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "repeat": "Cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.*, 5), 6)"
    }
   ]
  }
 ]
}