{
 "title": "NetApp HCI - SolidFire Volume",
 "description": "Volume performance metrics",
 "tags": [
  "SolidFire",
  "HCI"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "AccountID",
    "query": "netapp.solidfire.cluster.$Cluster.accountID.*"
   },
   {
    "name": "Volume",
    "query": "netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Size",
   "type": "singlestat",
   "description": "Larger volumes take longer to backup, snapshot, replicate.... \n\nBest practice: try to keep volumes much smaller than the current Element maximum of 16TB. ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.volumeSize"
    }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "target": "divideSeries(scale(#A, 4096), #C)",
     "targetFull": "divideSeries(scale(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.nonZeroBlocks, 4096), netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.volumeSize)"
    }
   ]
  },
  {
   "title": "Performance Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.volumeUtilization"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.throttle)"
    }
   ]
  },
  {
   "title": "%Read",
   "type": "gauge",
   "description": "Over a short period (say, 5 min), Read + Write % may not equal 100.\n\nUsers may want to increase QoS for volumes that have lower read percentage and hit Max IOPS (Throttle) more than comfortable",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "target": "alias(divideSeries(#A, #C), 'Pct Read')",
     "targetFull": "alias(divideSeries(aliasByMetric(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readOps), alias(sumSeries(#A, aliasByMetric(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeOps)), 'TotalOps')), 'Pct Read')"
    }
   ]
  },
  {
   "title": "%Write",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #C), 'Pct Write')"
    }
   ]
  },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readBytes), 'Read')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeBytes), 'Write')"
    }
   ]
  },
  {
   "title": "Volume IOPS and Average Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readOps), 'Read')"
    },
    {
     "target": "alias(perSecond(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeOps), 'Write')"
    },
    {
     "target": "alias(perSecond(sumSeries(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.*Ops)), 'Total')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.averageIOPSize, 'Avg IOP Size')"
    }
   ]
  },
  {
   "title": "Volume Latency and Queue Depth",
   "type": "graph",
   "description": "Volume latency is time taken to respond to received I/O requests. \n\nIt does not include RTT on the network and other overheads (hypervisor, container, etc.). Latency of non-cached I/O requests that application sees is always slightly higher\n\nVery low (e.g. 1) Queue Depth may indicate single-threaded application (if container or physical host is the iSCSI client). Persistently high 32 QD may indicate a very busy application that could benefit from having its data spread over several volumes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.readLatencyUSec, 'Read Latency')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.writeLatencyUSec, 'Write Latency')"
    },
    {
     "target": "alias(netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.clientQueueDepth, 'Queue Depth')"
    }
   ]
  }
 ]
}