{
 "title": "NetApp HCI - vSphere ESXi Metrics",
 "tags": [
  "HCI",
  "ESXi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vsphere.*" },
   { "name": "Host", "query": "vsphere.$vcenter.hostsystem.*" },
   { "name": "TopN", "query": "1,3,6,8" }
  ]
 },
 "panels": [
  { "title": "ESXi CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Host ESXi Average CPU Utilization (MHz)",
   "type": "graph",
   "description": "Average CPU utilization (MHz) of ESXi hosts",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CPU Mhz" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(vsphere.$vcenter.hostsystem.$Host.cpu.usagemhz.average, $TopN), 3)"
    }
   ]
  },
  {
   "title": "$Host ESXi CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.average, 0.01), $TopN), 3)"
    }
   ]
  },
  {
   "title": "$Host CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "Host",
   "targets": [
    {
     "target": "scale(vsphere.$vcenter.hostsystem.$Host.cpu.usage.maximum, 0.01)"
    }
   ]
  },
  { "title": "ESXi Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$Host ESXi Active Memory",
   "type": "graph",
   "description": "Active memory per ESXi host",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "deckbytes", "label": "Active Memory" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(vsphere.$vcenter.hostsystem.$Host.mem.active.maximum, $TopN), 3)"
    }
   ]
  },
  {
   "title": "$Host Memory Usage (%)",
   "type": "graph",
   "description": "Percentage of ESXi host memory that has been consumed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(scale(vsphere.$vcenter.hostsystem.$Host.mem.usage.maximum, 0.01), $TopN), 3)"
    }
   ]
  },
  { "title": "ESXi Datastore Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$Host ESXi Average Datastore IOPS",
   "type": "graph",
   "description": "Average Datastore IOPS for datastores attached to ESXi host. You may want to create own aliases to see datastore names",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "Host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(vsphere.$vcenter.hostsystem.$Host.datastore.datastoreiops.average.*)"
    }
   ]
  },
  {
   "title": "$Host ESXi Average I/O Latency",
   "type": "graph",
   "description": "Average  Datastore I/O  latency for naa_ * datastores attached to an ESXi host. You may want to create own aliases to use recognizable datastore names. \n\nVolume IDs are in hexadecimal notation. SolidFire volume naa_....011 is Volume ID 17 in the SolidFire Web management UI",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "repeat": "Host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "highestCurrent(aliasByMetric(vsphere.$vcenter.hostsystem.$Host.disk.devicelatency.average.naa_6f47acc*), $TopN)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}