{
 "title": "NetApp HCI - vSphere VM Stats",
 "tags": [
  "HCI",
  "ESXi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vsphere.*" },
   {
    "name": "VM",
    "query": "vsphere.$vcenter.virtualmachine.*"
   },
   { "name": "TopN", "label": "Top N VMs", "query": "1,3,5,10.,15" }
  ]
 },
 "panels": [
  { "title": "VM CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$VM CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(scale(vsphere.$vcenter.virtualmachine.$VM.cpu.usage.maximum, 0.01), $TopN), 3)"
    }
   ]
  },
  {
   "title": "$VM VM CPU Ready (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(scale(scale(vsphere.$vcenter.virtualmachine.$VM.cpu.ready.summation, 0.0000166), 100), $TopN), 3)"
    }
   ]
  },
  { "title": "VM Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "VM - Active Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(vsphere.$vcenter.virtualmachine.$VM.mem.active.maximum, $TopN), 3)"
    }
   ]
  },
  { "title": "VM Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$VM VM Total IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(#A, #B), 'Total IOPS')",
     "targetFull": "alias(sumSeries(vsphere.$vcenter.virtualmachine.$VM.virtualdisk.numberwriteaveraged.average.*, vsphere.$vcenter.virtualmachine.$VM.virtualdisk.numberreadaveraged.average.*), 'Total IOPS')"
    }
   ]
  },
  {
   "title": "VM Write IOPS  (Selected or Top $TopN)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(aliasByNode(vsphere.$vcenter.virtualmachine.$VM.virtualdisk.numberwriteaveraged.average.*, 3), 0, 'sum'), $TopN)"
    }
   ]
  },
  {
   "title": "VM Read IOPS (Selected or Top $TopN)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(highestAverage(vsphere.$vcenter.virtualmachine.$VM.virtualdisk.numberreadaveraged.average.*, $TopN), 3, 7), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Top $TopN or Selected VM by Write Latency",
   "type": "graph",
   "description": "A VM with N slow VMDKs will be listed once even though it may have Top N disks with highest write latency",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(vsphere.$vcenter.virtualmachine.$VM.virtualdisk.totalwritelatency.average.*, 3, 'sum'), $TopN)"
    }
   ]
  },
  {
   "title": "Top $TopN or Selected VM by Read Latency",
   "type": "graph",
   "description": "A VM with N slow VMDKs will be listed once even though it may have Top N disks with highest read latency",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "highestAverage(groupByNode(aliasByNode(vsphere.$vcenter.virtualmachine.$VM.virtualdisk.totalreadlatency.average.*, 3), 0, 'sum'), $TopN)"
    }
   ]
  }
 ]
}